---
## Benchmark ID
id: daa_benchmark

## Description
description: "Differential Abundance Analysis Benchmark"

## Version
version: 1.0

## Contact
benchmarker: "Lorenzo, lorenzofavaro.soa@gmail.com"

## Storage
storage_api: S3
storage: out

## Schema version
benchmark_yaml_spec: 0.01

## Software backend
software_backend: conda

## Software environments
software_environments:
  python:
    description: "data generation env"
    conda: envs/data_generation.yml
  r_limma:
    description: "R environment with limma"
    conda: envs/limma.yml

stages:
  ## Datasets
  - id: data
    modules:
      - id: s1
        name: 'synthetic_data'
        software_environment: "python"
        repository:
          url: "https://github.com/lorenzo-22/OmniBench-DAA_project"
          commit: bcd9362
    outputs:
      - id: data.matrix
        path: "data/synthetic_dataset.csv"

## Methods
  - id: methods
    modules:
      - id: limma
        name: 'limma_method'
        software_environment: "r_limma"
        repository:
          url: "https://github.com/lorenzo-22/limma_R-script"
          commit: 36f8f11
    inputs:
      - entries:
          - data.matrix
    outputs:
      - id: results
        path: "{dataset}_limma_results.csv"
