## Benchmark ID
id: daa_benchmark

## Description
description: "Differential Abundance Analysis Benchmark"

## Version
version: 1.0

## Contact
benchmarker: "Lorenzo, lorenzofavaro.soa@gmail.com"

## Storage
storage_api: S3
storage: out

## Schema version
benchmark_yaml_spec: 0.01

## Software backend
software_backend: conda

## Software environments
software_environments:
  python:
    description: "data generation env"
    conda: envs/data_generation.yml
  python_welch:
    description: "Basic python env for simple methods and tools. Includes basis libs such as scipy and numpy"
    conda: envs/python_welch.yml
  r_limma:
    description: "R environment with limma"
    conda: envs/limma.yml
  r_proda:
    description: "R environment with ProDA"
    conda: envs/r_ProDA.yml
  python_inter_tool_metrics:
    description: "Python environment for inter metrics calculation"
    conda: envs/python_inter_tool_metrics.yml
  python_intra_tool_metrics:
    description: "Python environment for intra-tool metrics calculation"
    conda: envs/python_intra_tool_metrics.yml

metric_collectors:
  - id: inter_tool_metrics
    name: "Metrics comparing data with no ground truth to one another"
    software_environment: "python_inter_tool_metrics"
    repository:
      url: https://github.com/lorenzo-22/inter_metrics
      commit: HEAD
    outputs:
      - id: plotting.html
        path: "{input}/{name}/plotting_report.html"

stages:
  ## Datasets
  - id: data
    modules:
      - id: synthetic
        name: 'synthetic_data'
        software_environment: "python"
        repository:
          url: "https://github.com/lorenzo-22/synthetic_dataset"
          commit: HEAD
      - id: semi-synthetic
        name: 'semi_synthetic_data'
        software_environment: "python"
        repository:
          url: "https://github.com/lorenzo-22/semi-synthetic_dataset"
          commit: HEAD
      - id: cancer
        name: 'cancer_data'
        software_environment: "python"
        repository:
          url: "https://github.com/lorenzo-22/cancer_dataset"
          commit: HEAD      
    outputs:
      - id: data.matrix
        path: "{input}/{stage}/{module}/{params}/{dataset}.dataset.csv"
      - id: data.true_labels
        path: "{input}/{stage}/{module}/{params}/{dataset}.true_labels.csv"
      - id: data.true_labels_proteins
        path: "{input}/{stage}/{module}/{params}/{dataset}.true_labels_proteins.csv"
  ## Methods
  - id: methods
    modules:
      - id: limma
        name: 'limma_method'
        software_environment: "r_limma"
        repository:
          url: "https://github.com/JosefineTM/DDA_limma"
          commit:  HEAD 
      - id: welch
        name: "welch_ttest"
        software_environment: "python_welch"
        repository:
          url: "https://github.com/lorenzo-22/welch_t-test"
          commit: HEAD
      - id: proda
        name: "ProDA"
        software_environment: "r_proda"
        repository:
          url: "https://github.com/JosefineTM/DDA_ProDA.git"
          commit: HEAD
    inputs:
      - entries:
          - data.matrix
          - data.true_labels
    outputs:
      - id: results
        path: "{input}/{stage}/{module}/{params}/{dataset}_results.csv"


  - id: intra_metrics
    modules:
      - id : intra_tool_metrics
        name: "intra_metrics"
        software_environment: "python_intra_tool_metrics" 
        repository:
          url: "https://github.com/lorenzo-22/intra_metrics"
          commit: HEAD
    inputs:
      - entries:
          - results
          - data.true_labels_proteins
    outputs:
      - id: inter_tool_metrics.scores
        path: "{input}/{stage}/{module}/{params}/{dataset}_metrics.csv"  
