---
## Benchmark ID
id: daa_benchmark

## Description
description: "Differential Abundance Analysis Benchmark"

## Version
version: 1.0

## Contact
benchmarker: "Lorenzo, lorenzofavaro.soa@gmail.com"

## Storage
storage_api: S3
storage: https://s3.example.com

## Schema version
benchmark_yaml_spec: 0.01

## Software backend
software_backend: conda

## Software environments
software_environments:
  python:
    description: "Python with pandas, scipy, statsmodels"
    conda: envs/welch_ttest.yml

stages:
  ## Datasets
 - id: data
  modules:
    - id: s1
      name: 'synthetic_data'
      software_environment: "python"
      repository:
        url:
        commit:
  outputs:
    - id: data.matrix
      path: "{dataset}.csv"

## Methods
